#!/usr/bin/env python3
"""
gen_noc_tests.py - Auto-generate NOC verification tests from JSON config database.

Usage:
    python gen_noc_tests.py --config ../config/noc_slave_config.json --output ../sv/test/
    python gen_noc_tests.py --config ../config/noc_slave_config.json --test legality --output ../sv/test/
    python gen_noc_tests.py --all --config ../config/noc_slave_config.json --output ../sv/test/

Generates:
    - noc_legality_test_auto.sv
    - noc_boundary_test_auto.sv
    - noc_burst_test_auto.sv
    - noc_outstanding_test_auto.sv
    - noc_random_traffic_test_auto.sv
"""

import json
import os
import sys
import argparse
from datetime import datetime

BURST_MAP = {
    "FIXED": "noc_unified_transaction::FIXED",
    "INCR":  "noc_unified_transaction::INCR",
    "WRAP":  "noc_unified_transaction::WRAP",
}

PROTO_MAP = {
    "AXI4":      "noc_unified_transaction::NOC_AXI4",
    "AXI4Lite":  "noc_unified_transaction::NOC_AXILITE",
    "AHBLite":   "noc_unified_transaction::NOC_AHBLITE",
    "APB4":      "noc_unified_transaction::NOC_APB4",
    "AvalonMM":  "noc_unified_transaction::NOC_AVALON_MM",
}

HEADER = """// AUTO-GENERATED by gen_noc_tests.py - DO NOT EDIT MANUALLY
// Generated: {timestamp}
// Source: {config_file}
//
// NOC {test_type} Test - Auto-generated from slave configuration

class noc_{test_name}_test_auto extends noc_test_base;

    `uvm_component_utils(noc_{test_name}_test_auto)

    function new(string name = "noc_{test_name}_test_auto", uvm_component parent);
        super.new(name, parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        // Override default config with JSON-loaded config
        load_config_from_json("{config_json_path}");
    endfunction

    task main_phase(uvm_phase phase);
        noc_{test_name}_seq_auto seq = noc_{test_name}_seq_auto::type_id::create("seq");
        phase.raise_objection(this);
        seq.start(m_env.m_vseqr);
        phase.drop_objection(this);
    endtask
endclass

class noc_{test_name}_seq_auto extends noc_virtual_sequence_base;
    `uvm_object_utils(noc_{test_name}_seq_auto)

    function new(string name = "noc_{test_name}_seq_auto");
        super.new(name);
    endfunction

    task body();
        noc_api_wrapper api = noc_api_wrapper::get();
        bit [1023:0] rdata;
"""

FOOTER = """
        `uvm_info("NOC_AUTO", "{test_type} test complete", UVM_LOW)
    endtask
endclass
"""


def parse_addr(addr_str):
    """Parse hex address string with optional underscores."""
    return int(addr_str.replace("_", ""), 16)


def generate_legality_test(config):
    """Generate legality test: valid boundaries + illegal addresses for each slave."""
    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Legality",
        test_name="legality",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated legality test...", UVM_LOW)\n\n'

    for slave in config["slaves"]:
        name = slave["name"]
        base = parse_addr(slave["base_addr"])
        limit = parse_addr(slave["addr_range"])
        end = base + limit - 1

        sv += f'        // === Slave: {name} [0x{base:08X} - 0x{end:08X}] ===\n'

        # Valid: base address read
        sv += f'        api.noc_read(.addr(64\'h{base:08X}), .data(rdata));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Read base addr 0x{base:08X}", UVM_MEDIUM)\n\n'

        # Valid: base address write
        sv += f'        api.noc_write(.addr(64\'h{base:08X}), .data(1024\'hA5A5_A5A5), .size(2));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Write base addr 0x{base:08X}", UVM_MEDIUM)\n\n'

        # Valid: end address
        sv += f'        api.noc_read(.addr(64\'h{end:08X}), .data(rdata));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Read end addr 0x{end:08X}", UVM_MEDIUM)\n\n'

        # Invalid: below range
        if base > 0:
            sv += f'        // Expect DECERR for illegal address below range\n'
            sv += f'        api.noc_read(.addr(64\'h{base-1:08X}), .data(rdata));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] Read below range 0x{base-1:08X} (expect DECERR)", UVM_MEDIUM)\n\n'

        # Invalid: above range
        sv += f'        // Expect DECERR for illegal address above range\n'
        sv += f'        api.noc_read(.addr(64\'h{end+1:08X}), .data(rdata));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Read above range 0x{end+1:08X} (expect DECERR)", UVM_MEDIUM)\n\n'

        # Unmapped address
        sv += f'        // Unmapped address (should get DECERR)\n'
        sv += f'        api.noc_read(.addr(64\'hDEAD_BEEF), .data(rdata));\n'
        sv += f'        `uvm_info("NOC_AUTO", "Unmapped address 0xDEAD_BEEF (expect DECERR)", UVM_MEDIUM)\n\n'

    sv += FOOTER.format(test_type="Legality")
    return sv


def generate_boundary_test(config):
    """Generate boundary test: 4KB crossing, range boundaries, wrap alignment."""
    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Boundary",
        test_name="boundary",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated boundary test...", UVM_LOW)\n\n'

    for slave in config["slaves"]:
        name = slave["name"]
        base = parse_addr(slave["base_addr"])
        limit = parse_addr(slave["addr_range"])
        end = base + limit - 1
        max_size = slave.get("max_size", 3)

        sv += f'        // === Slave: {name} [0x{base:08X} - 0x{end:08X}] ===\n'

        # 4KB boundary test
        near_4kb = (base & ~0xFFF) + 0xFF0  # 16 bytes before 4KB boundary
        if near_4kb >= base:
            sv += f'        // 4KB boundary crossing test (write near 4KB edge)\n'
            sv += f'        api.noc_burst_write(.addr(64\'h{near_4kb:08X}), .data(\'{{1024\'h0}}), .len(2), .size(3));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] 4KB boundary burst at 0x{near_4kb:08X}", UVM_MEDIUM)\n\n'

            sv += f'        api.noc_burst_read(.addr(64\'h{near_4kb:08X}), .data(rdata), .len(2), .size(3));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] 4KB boundary burst read at 0x{near_4kb:08X}", UVM_MEDIUM)\n\n'

        # Range boundary: near the end
        near_end = end - 32
        if near_end >= base:
            sv += f'        // Range boundary test\n'
            sv += f'        api.noc_burst_read(.addr(64\'h{near_end:08X}), .data(rdata), .len(3), .size(3));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] End-of-range burst at 0x{near_end:08X}", UVM_MEDIUM)\n\n'

        # Wrap boundary
        if "WRAP" in slave.get("supported_burst", []):
            wrap_addr = base & ~0xF  # align to 16-byte
            sv += f'        // Wrap boundary alignment test\n'
            sv += f'        api.noc_burst_read(.addr(64\'h{wrap_addr:08X}), .data(rdata), .len(3), .size(2), .burst(noc_unified_transaction::WRAP));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] Wrap burst at 0x{wrap_addr:08X}", UVM_MEDIUM)\n\n'

    sv += FOOTER.format(test_type="Boundary")
    return sv


def generate_burst_test(config):
    """Generate burst test: all supported burst types, lengths, sizes."""
    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Burst",
        test_name="burst",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated burst test...", UVM_LOW)\n\n'

    sizes_to_test = [2, 3]   # 32-bit, 64-bit

    for slave in config["slaves"]:
        name = slave["name"]
        base = parse_addr(slave["base_addr"])
        max_len = slave.get("max_len", 15)
        max_size = slave.get("max_size", 3)
        supported_bursts = slave.get("supported_burst", ["INCR"])

        sv += f'        // === Slave: {name} ===\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Burst test: bursts={supported_bursts} max_len={max_len} max_size={max_size}", UVM_MEDIUM)\n\n'

        for burst_type in supported_bursts:
            burst_macro = BURST_MAP.get(burst_type, "noc_unified_transaction::INCR")
            test_len = min(max_len, 15)
            test_size = min(max_size, 7)

            # Test short burst
            sv += f'        api.noc_burst_write(.addr(64\'h{base:08X}), .data(\'{{1024\'h0}}), .len({min(3, test_len)}), .size({test_size}), .burst({burst_macro}));\n'
            sv += f'        `uvm_info("NOC_AUTO", "[{name}] Burst {burst_type} short len={min(3, test_len)}", UVM_MEDIUM)\n\n'

            # Test full burst length
            if test_len > 3:
                sv += f'        api.noc_burst_read(.addr(64\'h{base:08X}), .data(rdata), .len({test_len}), .size({test_size}), .burst({burst_macro}));\n'
                sv += f'        `uvm_info("NOC_AUTO", "[{name}] Burst {burst_type} max len={test_len}", UVM_MEDIUM)\n\n'

            # Test all supported sizes
            for sz in [s for s in range(test_size + 1)][:4]:
                sv += f'        api.noc_burst_write(.addr(64\'h{base:08X}), .data(\'{{1024\'h0}}), .len({min(1, test_len)}), .size({sz}), .burst({burst_macro}));\n'
                sv += f'        `uvm_info("NOC_AUTO", "[{name}] Burst {burst_type} size={sz} ({(2**sz)*8}-bit)", UVM_MEDIUM)\n\n'

        # Single beat access
        sv += f'        api.noc_write(.addr(64\'h{base:08X}), .data(1024\'hBEEF_CAFE), .size({test_size}));\n'
        sv += f'        api.noc_read(.addr(64\'h{base:08X}), .data(rdata), .size({test_size}));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Single beat R/W", UVM_MEDIUM)\n\n'

    sv += FOOTER.format(test_type="Burst")
    return sv


def generate_outstanding_test(config):
    """Generate outstanding test: push transactions up to max outstanding capability."""
    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Outstanding",
        test_name="outstanding",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated outstanding test...", UVM_LOW)\n\n'

    for slave in config["slaves"]:
        name = slave["name"]
        base = parse_addr(slave["base_addr"])
        outstanding = slave.get("outstanding_capability", 16)

        if outstanding <= 0:
            continue

        sv += f'        // === Slave: {name} (outstanding={outstanding}) ===\n'

        # Sequential reads to fill outstanding queue
        sv += f'        // Sequential non-blocking reads up to outstanding limit\n'
        sv += f'        for (int i = 0; i < {min(outstanding + 2, 20)}; i++) begin\n'
        sv += f'            fork\n'
        sv += f'                api.noc_read(.addr(64\'h{base:08X} + (i * 64)), .data(rdata), .size(3));\n'
        sv += f'            join_none\n'
        sv += f'            `uvm_info("NOC_AUTO", "[{name}] Outstanding request #%0d", i), UVM_HIGH)\n'
        sv += f'        end\n'
        sv += f'        wait fork;\n\n'

        # Verify operation after outstanding drain
        sv += f'        api.noc_read(.addr(64\'h{base:08X}), .data(rdata), .size(2));\n'
        sv += f'        `uvm_info("NOC_AUTO", "[{name}] Post-outstanding read OK", UVM_MEDIUM)\n\n'

    sv += FOOTER.format(test_type="Outstanding")
    return sv


def generate_random_traffic_test(config):
    """Generate random traffic test: random transactions across all masters and slaves."""
    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Random Traffic",
        test_name="random_traffic",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated random traffic test...", UVM_LOW)\n\n'

    # Build access matrix lookup: slave_name -> [master_ids that can access]
    access_matrix = config.get("access_matrix", {})
    slave_to_masters = {}
    for slave in config["slaves"]:
        sname = slave["name"]
        slave_to_masters[sname] = []
        for master in config.get("masters", []):
            mname = master["name"]
            if sname in access_matrix.get(mname, []):
                slave_to_masters[sname].append(master["id"])

    # Generate random traffic respecting access matrix
    sv += '        // Random traffic respecting access matrix\n'
    sv += '        for (int iter = 0; iter < 100; iter++) begin\n'
    sv += '            case ($urandom_range(0, {}))\n'.format(len(config["slaves"]) - 1)

    for i, slave in enumerate(config["slaves"]):
        name = slave["name"]
        base = parse_addr(slave["base_addr"])
        limit = parse_addr(slave["addr_range"])
        allowed_masters = slave_to_masters.get(name, [])
        sv += f'                {i}: begin  // {name}\n'
        if allowed_masters:
            mid_list = ", ".join(str(m) for m in allowed_masters)
            sv += f'                    int mid = $urandom_range(0, {len(allowed_masters)-1}) ? {mid_list} : {allowed_masters[0]};  // pick valid master\n'
        else:
            sv += f'                    int mid = 0;  // no access_matrix, fallback\n'
        sv += f'                    if ($urandom_range(0, 1))\n'
        sv += f'                        api.noc_read(.addr(64\'h{base:08X} + ($urandom_range(0, {limit-16}))), .data(rdata), .size($urandom_range(0, {slave.get("max_size", 3)})), .master_id(mid));\n'
        sv += f'                    else\n'
        sv += f'                        api.noc_write(.addr(64\'h{base:08X} + ($urandom_range(0, {limit-16}))), .data($urandom() & 1024\'hFFFF_FFFF), .size($urandom_range(0, {slave.get("max_size", 3)})), .master_id(mid));\n'
        sv += f'                end\n'
    sv += '            endcase\n'
    sv += '        end\n\n'

    sv += FOOTER.format(test_type="Random Traffic")
    return sv


def generate_master_traverse_test(config):
    """Generate master traverse test: one master visits all slaves it can access."""
    masters_cfg = config.get("masters", [])
    access_matrix = config.get("access_matrix", {})

    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Master Traverse",
        test_name="master_traverse",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated master traverse test...", UVM_LOW)\n\n'

    for master in masters_cfg:
        mid = master["id"]
        mname = master["name"]
        allowed = access_matrix.get(mname, [])
        if not allowed:
            sv += f'        // Master[{mid}] "{mname}": no slaves in access matrix, skipping\n\n'
            continue

        sv += f'        // === Master[{mid}] "{mname}" traversing {len(allowed)} slaves ===\n'
        sv += f'        begin\n'
        sv += f'            noc_slave_config slvs[$];\n'
        sv += f'            m_cfg.find_slaves_for_master({mid}, slvs);\n'
        sv += f'            foreach (slvs[i]) begin\n'
        sv += f'                api.noc_write(.addr(slvs[i].base_addr), .data(1024\'hFEED_FACE), .size(2), .master_id({mid}));\n'
        sv += f'                api.noc_read(.addr(slvs[i].base_addr), .data(rdata), .size(2), .master_id({mid}));\n'
        sv += f'                `uvm_info("NOC_AUTO", $sformatf("M[{mid}]%s -> %s 0x%%0h", slvs[i].name, slvs[i].base_addr), UVM_MEDIUM)\n'
        sv += f'            end\n'
        sv += f'        end\n\n'

    sv += FOOTER.format(test_type="Master Traverse")
    return sv


def generate_conflict_test(config):
    """Generate conflict test: all accessible masters access one slave concurrently."""
    slaves_cfg = config.get("slaves", [])
    masters_cfg = config.get("masters", [])
    access_matrix = config.get("access_matrix", {})

    sv = HEADER.format(
        timestamp=datetime.now().isoformat(),
        config_file=config.get("_source", "noc_slave_config.json"),
        test_type="Conflict (Read/Write)",
        test_name="conflict",
        config_json_path="../config/noc_slave_config.json"
    )
    sv += '\n        `uvm_info("NOC_AUTO", "Starting auto-generated conflict test...", UVM_LOW)\n\n'

    for slave in slaves_cfg:
        sname = slave["name"]
        base = parse_addr(slave["base_addr"])
        limit = parse_addr(slave["addr_range"])

        # Find masters that can access this slave
        eligible = []
        for master in masters_cfg:
            mname = master["name"]
            if sname in access_matrix.get(mname, []):
                eligible.append(master)

        if len(eligible) <= 1:
            sv += f'        // Slave "{sname}": only {len(eligible)} master(s) can access, skipping conflict test\n\n'
            continue

        sv += f'        // === Slave "{sname}" conflict: {len(eligible)} masters ===\n'
        sv += f'        begin\n'
        sv += f'            `uvm_info("NOC_AUTO", "[{sname}] {len(eligible)} masters concurrent access", UVM_MEDIUM)\n'
        sv += f'            fork\n'

        for i, master in enumerate(eligible):
            mid = master["id"]
            mname = master["name"]
            taddr = base + (mid * 128)
            if taddr >= base + limit:
                taddr = base + (mid * 16)  # fallback in tight ranges
            sv += f'                begin  // M[{mid}] "{mname}"\n'
            sv += f'                    api.noc_write(.addr(64\'h{taddr:08X}), .data({{960\'h0, 64\'h({mid})}}), .size(3), .master_id({mid}));\n'
            sv += f'                    api.noc_read(.addr(64\'h{taddr:08X}), .data(rdata), .size(3), .master_id({mid}));\n'
            sv += f'                end\n'

        sv += f'            join\n'
        sv += f'        end\n\n'

        # Round 2: mixed read/write to same region
        sv += f'        // Mixed R/W to same slave\n'
        sv += f'        fork\n'
        for i, master in enumerate(eligible):
            mid = master["id"]
            taddr = base + (mid * 128)
            if taddr >= base + limit:
                taddr = base + (mid * 16)
            if mid % 2 == 0:
                sv += f'            api.noc_write(.addr(64\'h{taddr:08X}), .data(1024\'h0), .size(3), .master_id({mid}));  // M[{mid}]\n'
            else:
                sv += f'            api.noc_read(.addr(64\'h{taddr:08X}), .data(rdata), .size(3), .master_id({mid}));  // M[{mid}]\n'
        sv += f'        join\n\n'

    sv += FOOTER.format(test_type="Conflict (Read/Write)")
    return sv


TEST_GENERATORS = {
    "legality":         generate_legality_test,
    "boundary":         generate_boundary_test,
    "burst":            generate_burst_test,
    "outstanding":      generate_outstanding_test,
    "random_traffic":   generate_random_traffic_test,
    "master_traverse":  generate_master_traverse_test,
    "conflict":         generate_conflict_test,
}


def main():
    parser = argparse.ArgumentParser(description="Generate NOC verification tests from JSON config")
    parser.add_argument("--config", required=True, help="Path to noc_slave_config.json")
    parser.add_argument("--output", default="../sv/test/", help="Output directory for generated SV files")
    parser.add_argument("--test", choices=list(TEST_GENERATORS.keys()), help="Generate specific test only")
    parser.add_argument("--all", action="store_true", help="Generate all tests")
    args = parser.parse_args()

    if not args.test and not args.all:
        print("Specify --test <name> or --all")
        return 1

    # Load config
    with open(args.config, 'r') as f:
        config = json.load(f)
    config["_source"] = args.config

    os.makedirs(args.output, exist_ok=True)

    tests_to_gen = list(TEST_GENERATORS.keys()) if args.all else [args.test]

    for test_name in tests_to_gen:
        generator = TEST_GENERATORS[test_name]
        sv_code = generator(config)
        output_file = os.path.join(args.output, f"noc_{test_name}_test_auto.sv")
        with open(output_file, 'w') as f:
            f.write(sv_code)
        print(f"Generated: {output_file} ({len(sv_code)} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
